### ISSUE TITLE
`userId` or `userID`, what should we write?

### ISSUE THREAD

**Issue by limouren** [oursky/philosophy#1]
:P

**Comment by jimcky** [comment]
userId

Id is short for identifier which is only one word. each word should only add one capital letter to the abbreviation in camel case. 

IMHO.

**Comment by cheungpat** [comment]
That’s language and framework specific

**Comment by limouren** [comment]
@cheungpat maybe not:

1. Visit http://docs.oracle.com/javase/6/docs/api/index-files/index-7.html
2. Search `getID` and `getId`
3. :sake:

**Comment by cheungpat** [comment]
That’s why I say it is language *and* framework specific.

**Comment by cheungpat** [comment]
Love this one (non-capitalised “string”):
```
getIDstring() - Method in class java.awt.GraphicsDevice
Returns the identification string associated with this GraphicsDevice.
```

**Comment by chpapa** [comment]
Go official code review guide say always use getID

https://github.com/golang/go/wiki/CodeReviewComments

**Comment by rickmak** [comment]
Let's user `ID` within Oursky code base in future? Not only in Go, but also js.

Only use `Id` if the language and framework have specify otherwise.
